[package]
name = "watch_clipboard"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
image = "0.24"
arboard = "3.4.1"
dirs = "5.0.1"
uuid = { version = "1.3.0", features = ["v4"] }
which = "6.0.3"
native-dialog = "0.6.3"

[dev-dependencies]
tempfile = "3.8"
